CC = gcc -Wall -O1
PROGS = ./example01_rssi \
		./example02_led_at \
		./example03_led_gpo \
		./example04_led_px \
		./example05_sw_gpi \
		./example06_sw_r \
		./example07_sw_f \
		./example08_adc \
		./example09_adc_f \
		./example10_batt \
		./example11_pair \
		./example12_sw_r \
		./example13_sw_f \
		./example14_adc \
		./example15_adc_f \
		./example16_uart_tx \
		./example17_uart_rx \
		./example18_uart_trx \
		./example18_uart_trxc \
		./example19_led \
		./example20_enc \
		./example21_wall \
		./example22_sens \
		./example23_plug \
		./example24_mysns_f \
		./example25_mysns_r \
		./example26_log \
		./example27_plg_ctrl \
		./example28_plg_sns \
		./example29_bell \
		./example30_bell_sw \
		./example31_led \
		./example32_sw_r \
		./example33_sw_f \
		./example34_mysns \
		./example35_uart \
		./example36_15term \
		./example38_15bt_led \
		./example39_15bt_sens \
		./example40_15bt_car \
		./example41_15zb_sens \
		./example42_ble_scan \
		./example43_ble_read \
		./example44_ble_write \
		./example45_ble_prev \
		./example46_bt_led \
		./example47_bt_sw \
		./example48_bt_sns

all: $(PROGS)
		# ========================================
		# XBeeCoord examples for Raspberry Pi
		#                         by Wataru KUNINO
		# ========================================

clean:
	rm -f $(PROGS)
