CC = gcc -Wall -O1
PROGS = ./example01_rssi \
		./example02_led_at \
		./example03_led_gpo \
		./example04_led_px \
		./example05_sw_gpi \
		./example06_sw_r \
		./example07_sw_f \
		./example08_adc \
		./example09_adc_f \
		./example10_batt \
		./example11_pair \
		./example12_sw_r \
		./example13_sw_f \
		./example14_adc \
		./example15_adc_f \
		./example16_uart_tx \
		./example17_uart_rx \
		./example18_uart_trx \
		./example19_led \
		./example20_enc \
		./example21_wall \
		./example22_sens \
		./example23_plug \
		./example24_mysns_f \
		./example25_mysns_r \
		./example26_log \
		./example27_plg_ctrl \
		./example28_plg_sns \
		./example29_bell \
		./example30_bell_sw \
		./example30_bell_sw_r \
		./example66_rssi \
		./example67_led \
		./example68_sw_r \
		./example69_sw_f \
		./example70_uart \

all: $(PROGS)

clean:
	rm -f $(PROGS)
